name: smart_attendence_app
description: Attendance Capturing app which uses face auth to capture attendence
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  camera: ^0.10.0+5
  path: ^1.8.0
  animated_bottom_navigation_bar: ^1.1.0
  shared_preferences: any
  http: ^0.13.4
  font_awesome_flutter: ^10.1.0
  animated_text_kit: ^4.2.1
  animated_splash_screen: ^1.2.0
  percent_indicator: ^4.2.2
  fluttertoast: ^8.1.2
  intl: ^0.18.0
  stop_watch_timer: ^2.0.0
  dart_ipify: ^1.1.1

  syncfusion_flutter_charts: ^20.4.42
  flutter_face_api: ^4.1.1
  image_picker: ^0.8.6+1
  tflite_flutter: ^0.9.0
  google_ml_kit: 0.7.3
  image: 3.1.3
  local_auth: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: any
  http: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
